
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.doney
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:119.45.13.75}
      port: ${REDIS_PORT:6379}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        #注意这里两个数据库有对应的方言配置
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect